hand_max_closure: 19000
hand_grasp_trigger_dist: 0.04 # distance to the target goal which triggers the closure of the hand
hand_grasp_complete_dist: 0.03 # distance at which the grasp is complete (reaches qb_hand_max_closure)
