hand_max_closure: 19000
hand_grasp_trigger_dist: 0.06 # distance to the target goal which triggers the closure of the hand
hand_grasp_complete_dist: 0.03 # distance at which the grasp is complete (reaches qb_hand_max_closure)
guard_weight: 16 # w = m*g, this will be used to cancel the weight of the guard 
guard_ori_damp: .5 # this should be a positive double
filter_time_constant: 0.1 # should be more than 5*dt where dt is the frequency of the node
guard_rot_stiffness_follower: [2, 2, 2]
guard_rot_stiffness_obstacle: [4, 0.5, 4]
guard_rot_stiffness_disturbance: [0.5, 4, 0.5]
modulation_threshold: 0.1
disturbance_max_pow: 15
disturbance_min_pow: 2.5
disturbance_energy_threshold: 2
